### ISSUE TITLE
Configurer postcss

### ISSUE THREAD

**Issue by raphaelsanchez** [guidoline/guidoline.com#55]
- [x] Configurer postcss avec le fichier `postcss.config.js`
- [x] postcss-preset-env
- [x] postcss-flexbugs-fixes
- [x] postcss-custom-media
- [x] postcss-nested
- [x] postcss-custom-properties

**Comment by raphaelsanchez** [comment]
@ziopod j'ai terminé la configuration de postcss... je te laisse jeter un coup d'oeil et me dire si tout te va avant de close

**Comment by ziopod** [comment]
C'est ok pour moi.

Je te laisse choisir comment géré le fichiers CSS : 
 - un répertoire `styles` à la racine du projet ;
 - un simple fichier `layout.style.css` ou `global.css` dans le répertoire `app`.

Dans la mesure ou l'on devrait avoir que très peu de fichiers CSS globaux, je recommande la deuxième solution.

Documentation Next sur le sujet : https://nextjs.org/docs/app/building-your-application/styling/css-modules#global-styles


PS: le projet est configuré avec les deux solution pour le moment, n'ésite pas à supprimer les fichiers en trop.
